# Deploy a simple server that responds with a quote upon connection
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-servce
  namespace: development
  labels:
    app: quote-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-service
  template: 
    metadata:
      labels:
        app: quote-service
    spec:
      containers:
      - name: testing
        image: datawire/quote:0.5.0
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

        
