# Create a busybox pod in order to connect to and test the app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-busybox
  namespace: default
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: "busybox:latest"
        args:
          - sleep
          - "3600" # Keeps the container running for 1 hour
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

